### ISSUE TITLE
Backend TODO

### ISSUE THREAD

**Issue by arekpytka2812** [arekpytka2812/FootballGames#17]
BASED
- [x]  mian standings zrobić zeby najpierw order by punkty a potem bramki

USER

- [x]  Zmiana hasła użytkownika
- [x] Sciaganie klubów do enumów -> sciagane sa stringi (gacie)
- [x] ClubView naprawić

ADMIN
- [x]  update do zrobienia
- [x]  klasa query do przerobienia -> zrobic buildery
- [x]  delete do zobienia
- [x] do interfejsu tabel dodac metode getID() ktora bedzie zwracała id danej tabeli -> potrzebne przy delecie i updacie
- [x]  insert accounts trzeba zrobic zeby haszowało przed insertem
- [x]  dla update i delete sciaganie wybranego rekordu z myszki
- [x] dla tabel kontruktory z samym id -> chyba sprawdze jeszcze bo roket ide
