### ISSUE TITLE
Frontend TODO

### ISSUE THREAD

**Issue by mradamones** [arekpytka2812/FootballGames#26]
User:
- [x] Przeskalować wszystko na 1280x720
- [x] Potworzyć centery dla każdego widoku
- [x] Dodać sceny do enuma
Admin:
- [x] przefaktoryzować pole tekstowe (usunąć)
- [x] wybór konkretnej tabeli (combobox)
- [x] żeby ładowało updateQueryView przy zmianie enuma
